import type { VenueCandidate } from "@/lib/types";

export const venueCandidates: VenueCandidate[] = [
  {
    id: "seongsu-movie",
    name: "메가박스 성수",
    category: "movie",
    district: "성수",
    concept: "몰입형 스타트",
    description: "퇴근 후 바로 데이트 템포를 잡기 쉬운 상영관",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 118,
    estimatedCost: 24000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.5448,
    longitude: 127.0557,
    source: "mock",
    tags: ["실내", "몰입도", "역세권"],
  },
  {
    id: "seongsu-cafe",
    name: "모먼트 커피",
    category: "cafe",
    district: "성수",
    concept: "채광 좋은 대화형 카페",
    description: "좌석 간격이 넓고 대화가 편한 디저트 카페",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 60,
    estimatedCost: 16000,
    quietScore: 5,
    visualScore: 4,
    indoor: true,
    latitude: 37.5456,
    longitude: 127.0539,
    source: "mock",
    tags: ["조용함", "채광", "디저트"],
  },
  {
    id: "seongsu-cafe-alt",
    name: "아틀리에 티룸",
    category: "cafe",
    district: "성수",
    concept: "대기 짧은 티 디저트 카페",
    description: "조용한 좌석 구성이 강점이고 피크 시간대에도 회전이 빠른 티룸",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 55,
    estimatedCost: 14000,
    quietScore: 5,
    visualScore: 4,
    indoor: true,
    latitude: 37.5461,
    longitude: 127.0544,
    source: "mock",
    tags: ["조용함", "티룸", "웨이팅 분산"],
  },
  {
    id: "seongsu-dinner",
    name: "연무장 파스타",
    category: "dinner",
    district: "성수",
    concept: "안정적인 마무리 식사",
    description: "시끄럽지 않고 웨이팅 편차가 낮은 파스타 식당",
    transitMode: "walk",
    travelMinutes: 7,
    stayMinutes: 65,
    estimatedCost: 26000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.5442,
    longitude: 127.0568,
    source: "mock",
    tags: ["조용함", "웨이팅 안정", "대화 적합"],
  },
  {
    id: "seongsu-dinner-alt",
    name: "성수 스튜디오 키친",
    category: "dinner",
    district: "성수",
    concept: "예약 없이 들어가기 쉬운 저녁",
    description: "메뉴가 단순하고 회전이 빨라 웨이팅 리스크가 비교적 낮은 식당",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 60,
    estimatedCost: 22000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.5437,
    longitude: 127.0559,
    source: "mock",
    tags: ["회전 빠름", "예산 안정", "대화 적합"],
  },
  {
    id: "seongsu-bar",
    name: "오렌지 바틀",
    category: "bar",
    district: "성수",
    concept: "짧고 진한 2차",
    description: "칵테일 라인업이 안정적이고 조명이 과하지 않은 바",
    transitMode: "subway",
    travelMinutes: 8,
    stayMinutes: 72,
    estimatedCost: 18000,
    quietScore: 4,
    visualScore: 4,
    indoor: true,
    latitude: 37.5471,
    longitude: 127.0498,
    source: "mock",
    tags: ["칵테일", "무드 조명", "대화 적합"],
  },
  {
    id: "seongsu-gallery",
    name: "팩토리 전시룸",
    category: "gallery",
    district: "성수",
    concept: "공간감 있는 전시 스타트",
    description: "짧게 몰입하고 바로 카페로 이어가기 좋은 전시형 공간",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 58,
    estimatedCost: 18000,
    quietScore: 4,
    visualScore: 5,
    indoor: true,
    latitude: 37.5451,
    longitude: 127.0551,
    source: "mock",
    tags: ["사진 포인트", "실내", "몰입형"],
  },
  {
    id: "seongsu-walk",
    name: "서울숲 산책로",
    category: "walk",
    district: "성수",
    concept: "식사 후 짧은 전환",
    description: "성수 식사 후 가볍게 걸으며 대화를 이어가기 좋은 산책 코스",
    transitMode: "subway",
    travelMinutes: 8,
    stayMinutes: 30,
    estimatedCost: 0,
    quietScore: 4,
    visualScore: 4,
    indoor: false,
    latitude: 37.5444,
    longitude: 127.0376,
    source: "mock",
    tags: ["야외", "대화 연장", "분위기 전환"],
  },
  {
    id: "hongdae-movie",
    name: "CGV 홍대",
    category: "movie",
    district: "홍대",
    concept: "우천 대응형 시작점",
    description: "지하 연결 동선이 편한 홍대 중심 영화관",
    transitMode: "subway",
    travelMinutes: 3,
    stayMinutes: 125,
    estimatedCost: 22000,
    quietScore: 3,
    visualScore: 3,
    indoor: true,
    latitude: 37.5561,
    longitude: 126.9227,
    source: "mock",
    tags: ["지하 연결", "실내", "우천 대응"],
  },
  {
    id: "hongdae-cafe",
    name: "아케이드 라운지",
    category: "cafe",
    district: "홍대",
    concept: "실내 연결 라운지",
    description: "비 오는 날에도 동선이 끊기지 않는 북라운지 카페",
    transitMode: "walk",
    travelMinutes: 3,
    stayMinutes: 55,
    estimatedCost: 15000,
    quietScore: 5,
    visualScore: 3,
    indoor: true,
    latitude: 37.5565,
    longitude: 126.9238,
    source: "mock",
    tags: ["지하 연결", "조용함", "실내"],
  },
  {
    id: "hongdae-cafe-alt",
    name: "스테이 북카페",
    category: "cafe",
    district: "홍대",
    concept: "대기 분산형 북카페",
    description: "피크 시간에도 좌석 회전이 안정적인 북카페",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 50,
    estimatedCost: 13000,
    quietScore: 5,
    visualScore: 2,
    indoor: true,
    latitude: 37.5571,
    longitude: 126.9241,
    source: "mock",
    tags: ["조용함", "북카페", "웨이팅 분산"],
  },
  {
    id: "hongdae-dinner",
    name: "우동 작업실",
    category: "dinner",
    district: "홍대",
    concept: "저자극 저녁",
    description: "우천 시 만족도가 높은 따뜻한 메뉴 위주의 식당",
    transitMode: "bus",
    travelMinutes: 8,
    stayMinutes: 65,
    estimatedCost: 20000,
    quietScore: 4,
    visualScore: 2,
    indoor: true,
    latitude: 37.5552,
    longitude: 126.9198,
    source: "mock",
    tags: ["따뜻한 음식", "비 오는 날", "부담 적음"],
  },
  {
    id: "hongdae-dinner-alt",
    name: "라이트 누들 바",
    category: "dinner",
    district: "홍대",
    concept: "짧게 먹고 이동하기 쉬운 식사",
    description: "회전이 빠르고 메뉴 선택이 쉬운 누들 바",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 55,
    estimatedCost: 17000,
    quietScore: 3,
    visualScore: 2,
    indoor: true,
    latitude: 37.5558,
    longitude: 126.9215,
    source: "mock",
    tags: ["회전 빠름", "부담 적음", "실내"],
  },
  {
    id: "hongdae-bar",
    name: "홍대 포켓 바",
    category: "bar",
    district: "홍대",
    concept: "가볍게 시작하는 2차",
    description: "홍대 번화가에서 부담 없이 이어가기 좋은 소규모 바",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 55,
    estimatedCost: 16000,
    quietScore: 3,
    visualScore: 3,
    indoor: true,
    latitude: 37.5574,
    longitude: 126.9248,
    source: "mock",
    tags: ["캐주얼", "2차", "실내"],
  },
  {
    id: "hongdae-gallery",
    name: "플리마켓 갤러리",
    category: "gallery",
    district: "홍대",
    concept: "가볍게 즐기는 전시",
    description: "홍대 특유의 자유로운 분위기의 소규모 독립 갤러리",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 45,
    estimatedCost: 10000,
    quietScore: 3,
    visualScore: 4,
    indoor: true,
    latitude: 37.5567,
    longitude: 126.9232,
    source: "mock",
    tags: ["독립", "사진 포인트", "가볍게"],
  },
  {
    id: "hongdae-walk",
    name: "보드게임 아지트",
    category: "walk",
    district: "홍대",
    concept: "실내 활동 대체",
    description: "산책 대신 대화형 실내 활동으로 전환하기 좋은 공간",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 70,
    estimatedCost: 12000,
    quietScore: 3,
    visualScore: 3,
    indoor: true,
    latitude: 37.5578,
    longitude: 126.9255,
    source: "mock",
    tags: ["실내", "대화형", "가벼운 템포"],
  },
  {
    id: "gangnam-movie",
    name: "CGV 강남",
    category: "movie",
    district: "강남",
    concept: "소개팅 첫 단계",
    description: "강남역 접근성이 좋고 상영 편수가 많아 시간 선택이 유연한 영화관",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 120,
    estimatedCost: 24000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.4981,
    longitude: 127.0278,
    source: "mock",
    tags: ["역세권", "실내", "소개팅"],
  },
  {
    id: "gangnam-gallery",
    name: "신사 갤러리",
    category: "gallery",
    district: "강남",
    concept: "대화 소재가 되는 전시",
    description: "가로수길 인근 소규모 갤러리로 부담 없이 둘러보기 좋은 공간",
    transitMode: "subway",
    travelMinutes: 9,
    stayMinutes: 50,
    estimatedCost: 15000,
    quietScore: 4,
    visualScore: 4,
    indoor: true,
    latitude: 37.5211,
    longitude: 127.0227,
    source: "mock",
    tags: ["가로수길", "소규모", "대화형"],
  },
  {
    id: "gangnam-cafe",
    name: "세컨드 살롱",
    category: "cafe",
    district: "강남",
    concept: "소개팅 안전 카페",
    description: "배경 소음이 낮고 좌석 간격이 넓은 첫 만남용 카페",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 70,
    estimatedCost: 17000,
    quietScore: 5,
    visualScore: 3,
    indoor: true,
    latitude: 37.4982,
    longitude: 127.0284,
    source: "mock",
    tags: ["소음 낮음", "좌석 간격", "소개팅"],
  },
  {
    id: "gangnam-cafe-alt",
    name: "오브제 라운지",
    category: "cafe",
    district: "강남",
    concept: "피크 대응형 소개팅 카페",
    description: "좌석 수가 넓고 대기 분산이 되는 라운지형 카페",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 60,
    estimatedCost: 15000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.4987,
    longitude: 127.0296,
    source: "mock",
    tags: ["좌석 여유", "소개팅", "웨이팅 분산"],
  },
  {
    id: "gangnam-dinner",
    name: "스몰 플레이트 비스트로",
    category: "dinner",
    district: "강남",
    concept: "대화형 식사",
    description: "메뉴 결정 부담이 적고 조용한 좌석 구조를 가진 비스트로",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 73,
    estimatedCost: 24000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.4972,
    longitude: 127.0301,
    source: "mock",
    tags: ["예산 안정", "소개팅 안전", "대화 적합"],
  },
  {
    id: "gangnam-dinner-alt",
    name: "테이블 8 다이너",
    category: "dinner",
    district: "강남",
    concept: "웨이팅 적은 저녁 대안",
    description: "예약 없이도 비교적 빠르게 들어가기 좋은 식사 공간",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 62,
    estimatedCost: 21000,
    quietScore: 4,
    visualScore: 2,
    indoor: true,
    latitude: 37.4966,
    longitude: 127.0295,
    source: "mock",
    tags: ["회전 빠름", "예산 안정", "소개팅 안전"],
  },
  {
    id: "gangnam-walk",
    name: "도심 산책 루프",
    category: "walk",
    district: "강남",
    concept: "짧은 전환 산책",
    description: "식사 후 어색함을 풀고 대화를 이어가기 좋은 짧은 루프",
    transitMode: "walk",
    travelMinutes: 2,
    stayMinutes: 30,
    estimatedCost: 0,
    quietScore: 4,
    visualScore: 2,
    indoor: false,
    latitude: 37.4988,
    longitude: 127.0271,
    source: "mock",
    tags: ["분위기 전환", "대화 연장", "야외"],
  },
  {
    id: "gangnam-bar",
    name: "하이볼 스튜디오",
    category: "bar",
    district: "강남",
    concept: "가볍게 선택하는 2차",
    description: "부담 없는 잔술 위주로 이어가기 좋은 바",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 50,
    estimatedCost: 12000,
    quietScore: 3,
    visualScore: 3,
    indoor: true,
    latitude: 37.5003,
    longitude: 127.0312,
    source: "mock",
    tags: ["가볍게", "2차 선택형", "실내"],
  },
  {
    id: "eulji-movie",
    name: "씨네큐 을지로",
    category: "movie",
    district: "을지로",
    concept: "을지로형 시작점",
    description: "을지로 인근 중소형 상영관으로 피크 타임 웨이팅이 적은 편",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 115,
    estimatedCost: 22000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.5658,
    longitude: 126.9921,
    source: "mock",
    tags: ["실내", "웨이팅 적음", "역세권"],
  },
  {
    id: "eulji-gallery",
    name: "피크닉 전시관",
    category: "gallery",
    district: "을지로",
    concept: "감도 높은 스타트",
    description: "대화와 사진을 동시에 열어주는 전시형 장소",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 70,
    estimatedCost: 36000,
    quietScore: 4,
    visualScore: 5,
    indoor: true,
    latitude: 37.5643,
    longitude: 126.9797,
    source: "mock",
    tags: ["사진 포인트", "실내", "몰입형"],
  },
  {
    id: "eulji-cafe",
    name: "호텔 라운지 카페",
    category: "cafe",
    district: "을지로",
    concept: "디테일 있는 휴식",
    description: "식사 전 긴장을 풀고 분위기를 올리기 좋은 라운지",
    transitMode: "taxi",
    travelMinutes: 7,
    stayMinutes: 60,
    estimatedCost: 24000,
    quietScore: 4,
    visualScore: 5,
    indoor: true,
    latitude: 37.5652,
    longitude: 126.9814,
    source: "mock",
    tags: ["라운지", "뷰", "디저트"],
  },
  {
    id: "eulji-cafe-alt",
    name: "프레임 커피바",
    category: "cafe",
    district: "을지로",
    concept: "짧게 쉬는 무드 카페",
    description: "좌석 회전이 빨라 일정이 밀릴 때 대응하기 좋은 커피바",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 45,
    estimatedCost: 16000,
    quietScore: 3,
    visualScore: 4,
    indoor: true,
    latitude: 37.5657,
    longitude: 126.9808,
    source: "mock",
    tags: ["회전 빠름", "무드 조명", "실내"],
  },
  {
    id: "eulji-dinner",
    name: "르 시엘 다이닝",
    category: "dinner",
    district: "을지로",
    concept: "야간 무드 강화",
    description: "야경과 서비스 모두 강점인 기념일용 다이닝",
    transitMode: "taxi",
    travelMinutes: 9,
    stayMinutes: 95,
    estimatedCost: 68000,
    quietScore: 4,
    visualScore: 5,
    indoor: true,
    latitude: 37.5661,
    longitude: 126.9821,
    source: "mock",
    tags: ["야경", "기념일", "예약 추천"],
  },
  {
    id: "eulji-dinner-alt",
    name: "을지 다이닝 스튜디오",
    category: "dinner",
    district: "을지로",
    concept: "기념일 톤을 유지하는 대안 식사",
    description: "야경보다는 안정적인 좌석 운영이 강점인 다이닝",
    transitMode: "walk",
    travelMinutes: 7,
    stayMinutes: 78,
    estimatedCost: 42000,
    quietScore: 4,
    visualScore: 4,
    indoor: true,
    latitude: 37.5654,
    longitude: 126.9817,
    source: "mock",
    tags: ["무드 유지", "웨이팅 완화", "실내"],
  },
  {
    id: "eulji-bar",
    name: "레코드 하이볼",
    category: "bar",
    district: "을지로",
    concept: "퇴근 후 가볍게 이어지는 2차",
    description: "하이볼과 음악이 강점인 을지로형 캐주얼 바",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 55,
    estimatedCost: 15000,
    quietScore: 3,
    visualScore: 4,
    indoor: true,
    latitude: 37.5668,
    longitude: 126.9904,
    source: "mock",
    tags: ["하이볼", "캐주얼", "실내"],
  },
  {
    id: "eulji-walk",
    name: "청계 루프 산책",
    category: "walk",
    district: "을지로",
    concept: "짧게 정리하는 야간 산책",
    description: "식사나 술 이후 템포를 부드럽게 정리하기 좋은 짧은 산책 루프",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 28,
    estimatedCost: 0,
    quietScore: 4,
    visualScore: 3,
    indoor: false,
    latitude: 37.5681,
    longitude: 126.9889,
    source: "mock",
    tags: ["야간 무드", "대화 연장", "야외"],
  },
  // 이태원
  {
    id: "itaewon-movie",
    name: "CGV 용산아이파크몰",
    category: "movie",
    district: "이태원",
    concept: "이태원 접근성 좋은 상영관",
    description: "용산아이파크몰 내 위치해 이태원 데이트 시작점으로 동선이 자연스러운 영화관",
    transitMode: "subway",
    travelMinutes: 8,
    stayMinutes: 120,
    estimatedCost: 24000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.5328,
    longitude: 126.9640,
    source: "mock",
    tags: ["실내", "역세권", "몰입도"],
  },
  {
    id: "itaewon-cafe",
    name: "루프탑 필터드",
    category: "cafe",
    district: "이태원",
    concept: "이국적인 루프탑 커피",
    description: "이태원 특유의 이국적 감성이 느껴지는 루프탑 카페로 야외 좌석에서 뷰가 좋음",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 60,
    estimatedCost: 18000,
    quietScore: 3,
    visualScore: 5,
    indoor: true,
    latitude: 37.5345,
    longitude: 126.9952,
    source: "mock",
    tags: ["루프탑", "뷰", "이국적"],
  },
  {
    id: "itaewon-cafe-alt",
    name: "경리단길 소이 카페",
    category: "cafe",
    district: "이태원",
    concept: "골목 감성 카페",
    description: "경리단길 골목의 다국적 감성이 살아있는 소규모 카페, 영어 메뉴 제공",
    transitMode: "walk",
    travelMinutes: 7,
    stayMinutes: 55,
    estimatedCost: 16000,
    quietScore: 4,
    visualScore: 4,
    indoor: true,
    latitude: 37.5351,
    longitude: 126.9962,
    source: "mock",
    tags: ["골목", "다국적", "영어메뉴"],
  },
  {
    id: "itaewon-dinner",
    name: "이태원 타코 앤 타파스",
    category: "dinner",
    district: "이태원",
    concept: "다국적 분위기 식사",
    description: "영어 메뉴와 다국적 요리로 특별한 식사 경험을 제공하는 이태원 대표 레스토랑",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 70,
    estimatedCost: 32000,
    quietScore: 3,
    visualScore: 4,
    indoor: true,
    latitude: 37.5340,
    longitude: 126.9955,
    source: "mock",
    tags: ["다국적", "영어메뉴", "이태원 특색"],
  },
  {
    id: "itaewon-dinner-alt",
    name: "해밀턴 그릴",
    category: "dinner",
    district: "이태원",
    concept: "이태원 스테이크 하우스",
    description: "해밀턴호텔 인근 캐주얼 스테이크 그릴, 웨이팅 없이 들어가기 비교적 쉬운 편",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 65,
    estimatedCost: 38000,
    quietScore: 3,
    visualScore: 3,
    indoor: true,
    latitude: 37.5335,
    longitude: 126.9943,
    source: "mock",
    tags: ["스테이크", "캐주얼", "회전 적당"],
  },
  {
    id: "itaewon-bar",
    name: "루프탑 나인",
    category: "bar",
    district: "이태원",
    concept: "야경 루프탑 바",
    description: "이태원 전경이 내려다보이는 루프탑 바로 칵테일과 야경이 강점",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 70,
    estimatedCost: 22000,
    quietScore: 3,
    visualScore: 5,
    indoor: true,
    latitude: 37.5338,
    longitude: 126.9948,
    source: "mock",
    tags: ["루프탑", "야경", "칵테일"],
  },
  {
    id: "itaewon-gallery",
    name: "리움 미술관",
    category: "gallery",
    district: "이태원",
    concept: "세계적 수준의 미술 감상",
    description: "이태원 언덕의 삼성 리움 미술관, 국내외 현대미술 컬렉션으로 대화 소재가 풍부함",
    transitMode: "walk",
    travelMinutes: 10,
    stayMinutes: 75,
    estimatedCost: 20000,
    quietScore: 5,
    visualScore: 5,
    indoor: true,
    latitude: 37.5375,
    longitude: 126.9994,
    source: "mock",
    tags: ["미술관", "현대미술", "문화"],
  },
  {
    id: "itaewon-walk",
    name: "이태원 골목 산책",
    category: "walk",
    district: "이태원",
    concept: "다문화 골목 탐방",
    description: "이태원 특유의 다국적 상점과 음식점이 즐비한 골목을 가볍게 산책하는 코스",
    transitMode: "walk",
    travelMinutes: 3,
    stayMinutes: 30,
    estimatedCost: 0,
    quietScore: 3,
    visualScore: 4,
    indoor: false,
    latitude: 37.5340,
    longitude: 126.9947,
    source: "mock",
    tags: ["야외", "다문화", "골목 탐방"],
  },
  // 합정
  {
    id: "hapjeong-movie",
    name: "메가박스 합정",
    category: "movie",
    district: "합정",
    concept: "합정 인디 감성 시작점",
    description: "합정역 인근 중형 상영관으로 indie 분위기와 어울리는 영화 상영 다수",
    transitMode: "subway",
    travelMinutes: 5,
    stayMinutes: 118,
    estimatedCost: 22000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.5490,
    longitude: 126.9128,
    source: "mock",
    tags: ["실내", "역세권", "인디 감성"],
  },
  {
    id: "hapjeong-cafe",
    name: "빈티지 플리즈",
    category: "cafe",
    district: "합정",
    concept: "합정 빈티지 소품 카페",
    description: "옛 가구와 소품으로 꾸며진 아늑한 빈티지 카페, 조용한 대화에 최적",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 65,
    estimatedCost: 15000,
    quietScore: 5,
    visualScore: 4,
    indoor: true,
    latitude: 37.5501,
    longitude: 126.9148,
    source: "mock",
    tags: ["빈티지", "조용함", "소품"],
  },
  {
    id: "hapjeong-cafe-alt",
    name: "독립서점 카페 더 페이지",
    category: "cafe",
    district: "합정",
    concept: "독립출판 서점 겸 카페",
    description: "독립 서적과 아트 잡지가 가득한 서점형 카페로 합정의 예술적 감성이 물씬",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 60,
    estimatedCost: 13000,
    quietScore: 5,
    visualScore: 3,
    indoor: true,
    latitude: 37.5505,
    longitude: 126.9135,
    source: "mock",
    tags: ["독립서점", "조용함", "예술적"],
  },
  {
    id: "hapjeong-dinner",
    name: "합정 소반",
    category: "dinner",
    district: "합정",
    concept: "한식 정갈한 저녁",
    description: "합정 골목의 작은 한식 다이닝, 계절 재료로 만드는 코스형 한정식",
    transitMode: "walk",
    travelMinutes: 7,
    stayMinutes: 75,
    estimatedCost: 35000,
    quietScore: 5,
    visualScore: 4,
    indoor: true,
    latitude: 37.5493,
    longitude: 126.9140,
    source: "mock",
    tags: ["한식", "조용함", "계절 요리"],
  },
  {
    id: "hapjeong-dinner-alt",
    name: "파스타 앳 합정",
    category: "dinner",
    district: "합정",
    concept: "합정 캐주얼 이탈리안",
    description: "소규모 인테리어로 아늑한 분위기의 캐주얼 이탈리안 레스토랑",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 65,
    estimatedCost: 26000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.5498,
    longitude: 126.9151,
    source: "mock",
    tags: ["이탈리안", "아늑함", "소규모"],
  },
  {
    id: "hapjeong-bar",
    name: "와인 셀러 합정",
    category: "bar",
    district: "합정",
    concept: "조용한 와인 바",
    description: "합정 특유의 차분한 감성의 소규모 와인 바, 대화에 집중하기 좋은 환경",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 65,
    estimatedCost: 20000,
    quietScore: 5,
    visualScore: 3,
    indoor: true,
    latitude: 37.5502,
    longitude: 126.9145,
    source: "mock",
    tags: ["와인", "조용함", "소규모"],
  },
  {
    id: "hapjeong-gallery",
    name: "상수 아트 스페이스",
    category: "gallery",
    district: "합정",
    concept: "합정 인디 갤러리",
    description: "합정·상수 경계의 독립 예술가 전시 공간, 작가와 직접 대화할 수 있는 소규모 갤러리",
    transitMode: "walk",
    travelMinutes: 8,
    stayMinutes: 50,
    estimatedCost: 8000,
    quietScore: 5,
    visualScore: 4,
    indoor: true,
    latitude: 37.5510,
    longitude: 126.9160,
    source: "mock",
    tags: ["독립 갤러리", "인디", "예술가"],
  },
  {
    id: "hapjeong-walk",
    name: "한강 망원 산책로",
    category: "walk",
    district: "합정",
    concept: "한강변 여유 산책",
    description: "합정에서 걸어갈 수 있는 망원 한강공원 산책로, 저녁 노을이 아름다운 코스",
    transitMode: "walk",
    travelMinutes: 12,
    stayMinutes: 35,
    estimatedCost: 0,
    quietScore: 4,
    visualScore: 5,
    indoor: false,
    latitude: 37.5520,
    longitude: 126.9050,
    source: "mock",
    tags: ["한강", "야외", "노을"],
  },
  // 건대
  {
    id: "kondae-movie",
    name: "롯데시네마 건대입구",
    category: "movie",
    district: "건대",
    concept: "건대 대형 복합몰 영화관",
    description: "스타시티 내 위치한 롯데시네마, 건대 데이트의 시작으로 편리한 접근성",
    transitMode: "subway",
    travelMinutes: 4,
    stayMinutes: 120,
    estimatedCost: 23000,
    quietScore: 3,
    visualScore: 3,
    indoor: true,
    latitude: 37.5405,
    longitude: 127.0693,
    source: "mock",
    tags: ["복합몰", "역세권", "실내"],
  },
  {
    id: "kondae-cafe",
    name: "자양 로스터리",
    category: "cafe",
    district: "건대",
    concept: "대학가 스페셜티 카페",
    description: "건대 인근 직접 로스팅하는 스페셜티 커피 전문점, 가성비와 퀄리티 모두 만족",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 55,
    estimatedCost: 12000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.5408,
    longitude: 127.0710,
    source: "mock",
    tags: ["스페셜티", "가성비", "로스터리"],
  },
  {
    id: "kondae-cafe-alt",
    name: "건대 디저트 팩토리",
    category: "cafe",
    district: "건대",
    concept: "인스타 디저트 카페",
    description: "비주얼 디저트로 유명한 건대 핫플, 젊은 감각의 인테리어와 포토 스팟 보유",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 50,
    estimatedCost: 14000,
    quietScore: 3,
    visualScore: 4,
    indoor: true,
    latitude: 37.5397,
    longitude: 127.0705,
    source: "mock",
    tags: ["디저트", "인스타", "젊은 감성"],
  },
  {
    id: "kondae-dinner",
    name: "건대 고기마당",
    category: "dinner",
    district: "건대",
    concept: "활기찬 고기 구이",
    description: "건대 특유의 활기찬 분위기의 고기 구이 전문점, 가성비 좋고 웨이팅 시간 적당",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 70,
    estimatedCost: 28000,
    quietScore: 2,
    visualScore: 3,
    indoor: true,
    latitude: 37.5401,
    longitude: 127.0698,
    source: "mock",
    tags: ["고기구이", "가성비", "활기참"],
  },
  {
    id: "kondae-dinner-alt",
    name: "스시 미소카",
    category: "dinner",
    district: "건대",
    concept: "건대 가성비 스시",
    description: "대학가 수준을 뛰어넘는 품질의 캐주얼 스시 식당, 젊은 층에게 인기",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 65,
    estimatedCost: 32000,
    quietScore: 3,
    visualScore: 3,
    indoor: true,
    latitude: 37.5395,
    longitude: 127.0688,
    source: "mock",
    tags: ["스시", "캐주얼", "가성비"],
  },
  {
    id: "kondae-bar",
    name: "홉 하우스 건대",
    category: "bar",
    district: "건대",
    concept: "건대 크래프트 비어 펍",
    description: "다양한 크래프트 맥주를 합리적 가격에 즐길 수 있는 건대 인기 펍",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 60,
    estimatedCost: 16000,
    quietScore: 2,
    visualScore: 3,
    indoor: true,
    latitude: 37.5410,
    longitude: 127.0702,
    source: "mock",
    tags: ["크래프트 맥주", "활기참", "가성비"],
  },
  {
    id: "kondae-gallery",
    name: "건국대 예술 전시관",
    category: "gallery",
    district: "건대",
    concept: "대학 갤러리 산책",
    description: "건국대학교 내 예술 전시관, 학생 작품 전시부터 외부 초청 전시까지 다양한 프로그램",
    transitMode: "walk",
    travelMinutes: 10,
    stayMinutes: 45,
    estimatedCost: 0,
    quietScore: 4,
    visualScore: 4,
    indoor: true,
    latitude: 37.5428,
    longitude: 127.0726,
    source: "mock",
    tags: ["대학 갤러리", "학생 작품", "무료"],
  },
  {
    id: "kondae-walk",
    name: "어린이대공원 산책",
    category: "walk",
    district: "건대",
    concept: "도심 공원 산책",
    description: "건대에서 가깝고 넓은 어린이대공원, 가볍게 걸으며 대화 나누기 좋은 코스",
    transitMode: "subway",
    travelMinutes: 8,
    stayMinutes: 35,
    estimatedCost: 0,
    quietScore: 4,
    visualScore: 3,
    indoor: false,
    latitude: 37.5480,
    longitude: 127.0791,
    source: "mock",
    tags: ["공원", "야외", "여유로움"],
  },
  // 잠실
  {
    id: "jamsil-movie",
    name: "롯데시네마 월드타워",
    category: "movie",
    district: "잠실",
    concept: "잠실 대형 프리미엄 영화관",
    description: "롯데월드타워 내 프리미엄 영화관, 잠실 데이트 코스의 완벽한 출발점",
    transitMode: "subway",
    travelMinutes: 5,
    stayMinutes: 125,
    estimatedCost: 26000,
    quietScore: 4,
    visualScore: 4,
    indoor: true,
    latitude: 37.5128,
    longitude: 127.1023,
    source: "mock",
    tags: ["프리미엄", "복합몰", "실내"],
  },
  {
    id: "jamsil-cafe",
    name: "스카이31 라운지 카페",
    category: "cafe",
    district: "잠실",
    concept: "잠실 뷰 카페",
    description: "잠실 일대를 내려다보는 고층 라운지 카페, 한강과 롯데월드타워 뷰가 인상적",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 65,
    estimatedCost: 22000,
    quietScore: 4,
    visualScore: 5,
    indoor: true,
    latitude: 37.5120,
    longitude: 127.1028,
    source: "mock",
    tags: ["뷰 카페", "한강 뷰", "라운지"],
  },
  {
    id: "jamsil-cafe-alt",
    name: "석촌호수 카페 라 떼르",
    category: "cafe",
    district: "잠실",
    concept: "호수 뷰 여유 카페",
    description: "석촌호수 바로 옆의 넓은 창을 가진 카페, 호수를 바라보며 여유로운 대화 가능",
    transitMode: "walk",
    travelMinutes: 8,
    stayMinutes: 60,
    estimatedCost: 17000,
    quietScore: 4,
    visualScore: 4,
    indoor: true,
    latitude: 37.5097,
    longitude: 127.0996,
    source: "mock",
    tags: ["호수뷰", "여유로움", "대화 적합"],
  },
  {
    id: "jamsil-dinner",
    name: "잠실 더 플레이스",
    category: "dinner",
    district: "잠실",
    concept: "잠실 특별 다이닝",
    description: "롯데월드 인근의 분위기 있는 다이닝 레스토랑, 가족·커플 모두 즐기기 좋은 메뉴 구성",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 75,
    estimatedCost: 38000,
    quietScore: 4,
    visualScore: 4,
    indoor: true,
    latitude: 37.5138,
    longitude: 127.1005,
    source: "mock",
    tags: ["다이닝", "분위기 있음", "커플"],
  },
  {
    id: "jamsil-dinner-alt",
    name: "한강 치맥 스팟",
    category: "dinner",
    district: "잠실",
    concept: "한강 뷰 치킨 & 맥주",
    description: "잠실 한강공원 인근의 치킨 전문점, 한강을 보며 편하게 즐기는 가성비 식사",
    transitMode: "walk",
    travelMinutes: 9,
    stayMinutes: 65,
    estimatedCost: 22000,
    quietScore: 3,
    visualScore: 4,
    indoor: false,
    latitude: 37.5162,
    longitude: 127.0845,
    source: "mock",
    tags: ["한강뷰", "치맥", "가성비"],
  },
  {
    id: "jamsil-bar",
    name: "루프탑 바 120",
    category: "bar",
    district: "잠실",
    concept: "잠실 야경 루프탑 바",
    description: "잠실 고층 빌딩에서 즐기는 야경 루프탑 바, 칵테일과 야경의 조합이 일품",
    transitMode: "walk",
    travelMinutes: 7,
    stayMinutes: 70,
    estimatedCost: 25000,
    quietScore: 3,
    visualScore: 5,
    indoor: true,
    latitude: 37.5130,
    longitude: 127.1008,
    source: "mock",
    tags: ["루프탑", "야경", "칵테일"],
  },
  {
    id: "jamsil-gallery",
    name: "롯데뮤지엄",
    category: "gallery",
    district: "잠실",
    concept: "잠실 대형 미술관",
    description: "롯데월드타워 7층의 현대미술 전문 미술관, 대형 기획전과 인터랙티브 전시가 특징",
    transitMode: "subway",
    travelMinutes: 5,
    stayMinutes: 80,
    estimatedCost: 20000,
    quietScore: 4,
    visualScore: 5,
    indoor: true,
    latitude: 37.5126,
    longitude: 127.1024,
    source: "mock",
    tags: ["현대미술", "대형 전시", "인터랙티브"],
  },
  {
    id: "jamsil-walk",
    name: "석촌호수 산책로",
    category: "walk",
    district: "잠실",
    concept: "호수 둘레 산책",
    description: "잠실 석촌호수를 한 바퀴 돌며 산책하는 코스, 봄에는 벚꽃, 야간에는 조명이 아름다움",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 35,
    estimatedCost: 0,
    quietScore: 4,
    visualScore: 5,
    indoor: false,
    latitude: 37.5097,
    longitude: 127.0994,
    source: "mock",
    tags: ["호수 산책", "벚꽃", "야외"],
  },
];
