import type { VenueCandidate } from "@/lib/types";

export const venueCandidates: VenueCandidate[] = [
  {
    id: "seongsu-movie",
    name: "메가박스 성수",
    category: "movie",
    district: "성수",
    concept: "몰입형 스타트",
    description: "퇴근 후 바로 데이트 템포를 잡기 쉬운 상영관",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 118,
    estimatedCost: 24000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.5448,
    longitude: 127.0557,
    source: "mock",
    tags: ["실내", "몰입도", "역세권"],
  },
  {
    id: "seongsu-cafe",
    name: "모먼트 커피",
    category: "cafe",
    district: "성수",
    concept: "채광 좋은 대화형 카페",
    description: "좌석 간격이 넓고 대화가 편한 디저트 카페",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 60,
    estimatedCost: 16000,
    quietScore: 5,
    visualScore: 4,
    indoor: true,
    latitude: 37.5456,
    longitude: 127.0539,
    source: "mock",
    tags: ["조용함", "채광", "디저트"],
  },
  {
    id: "seongsu-cafe-alt",
    name: "아틀리에 티룸",
    category: "cafe",
    district: "성수",
    concept: "대기 짧은 티 디저트 카페",
    description: "조용한 좌석 구성이 강점이고 피크 시간대에도 회전이 빠른 티룸",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 55,
    estimatedCost: 14000,
    quietScore: 5,
    visualScore: 4,
    indoor: true,
    latitude: 37.5461,
    longitude: 127.0544,
    source: "mock",
    tags: ["조용함", "티룸", "웨이팅 분산"],
  },
  {
    id: "seongsu-dinner",
    name: "연무장 파스타",
    category: "dinner",
    district: "성수",
    concept: "안정적인 마무리 식사",
    description: "시끄럽지 않고 웨이팅 편차가 낮은 파스타 식당",
    transitMode: "walk",
    travelMinutes: 7,
    stayMinutes: 65,
    estimatedCost: 26000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.5442,
    longitude: 127.0568,
    source: "mock",
    tags: ["조용함", "웨이팅 안정", "대화 적합"],
  },
  {
    id: "seongsu-dinner-alt",
    name: "성수 스튜디오 키친",
    category: "dinner",
    district: "성수",
    concept: "예약 없이 들어가기 쉬운 저녁",
    description: "메뉴가 단순하고 회전이 빨라 웨이팅 리스크가 비교적 낮은 식당",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 60,
    estimatedCost: 22000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.5437,
    longitude: 127.0559,
    source: "mock",
    tags: ["회전 빠름", "예산 안정", "대화 적합"],
  },
  {
    id: "seongsu-bar",
    name: "오렌지 바틀",
    category: "bar",
    district: "성수",
    concept: "짧고 진한 2차",
    description: "칵테일 라인업이 안정적이고 조명이 과하지 않은 바",
    transitMode: "subway",
    travelMinutes: 8,
    stayMinutes: 72,
    estimatedCost: 18000,
    quietScore: 4,
    visualScore: 4,
    indoor: true,
    latitude: 37.5471,
    longitude: 127.0498,
    source: "mock",
    tags: ["칵테일", "무드 조명", "대화 적합"],
  },
  {
    id: "seongsu-gallery",
    name: "팩토리 전시룸",
    category: "gallery",
    district: "성수",
    concept: "공간감 있는 전시 스타트",
    description: "짧게 몰입하고 바로 카페로 이어가기 좋은 전시형 공간",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 58,
    estimatedCost: 18000,
    quietScore: 4,
    visualScore: 5,
    indoor: true,
    latitude: 37.5451,
    longitude: 127.0551,
    source: "mock",
    tags: ["사진 포인트", "실내", "몰입형"],
  },
  {
    id: "hongdae-movie",
    name: "CGV 홍대",
    category: "movie",
    district: "홍대",
    concept: "우천 대응형 시작점",
    description: "지하 연결 동선이 편한 홍대 중심 영화관",
    transitMode: "subway",
    travelMinutes: 3,
    stayMinutes: 125,
    estimatedCost: 22000,
    quietScore: 3,
    visualScore: 3,
    indoor: true,
    latitude: 37.5561,
    longitude: 126.9227,
    source: "mock",
    tags: ["지하 연결", "실내", "우천 대응"],
  },
  {
    id: "hongdae-cafe",
    name: "아케이드 라운지",
    category: "cafe",
    district: "홍대",
    concept: "실내 연결 라운지",
    description: "비 오는 날에도 동선이 끊기지 않는 북라운지 카페",
    transitMode: "walk",
    travelMinutes: 3,
    stayMinutes: 55,
    estimatedCost: 15000,
    quietScore: 5,
    visualScore: 3,
    indoor: true,
    latitude: 37.5565,
    longitude: 126.9238,
    source: "mock",
    tags: ["지하 연결", "조용함", "실내"],
  },
  {
    id: "hongdae-cafe-alt",
    name: "스테이 북카페",
    category: "cafe",
    district: "홍대",
    concept: "대기 분산형 북카페",
    description: "피크 시간에도 좌석 회전이 안정적인 북카페",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 50,
    estimatedCost: 13000,
    quietScore: 5,
    visualScore: 2,
    indoor: true,
    latitude: 37.5571,
    longitude: 126.9241,
    source: "mock",
    tags: ["조용함", "북카페", "웨이팅 분산"],
  },
  {
    id: "hongdae-dinner",
    name: "우동 작업실",
    category: "dinner",
    district: "홍대",
    concept: "저자극 저녁",
    description: "우천 시 만족도가 높은 따뜻한 메뉴 위주의 식당",
    transitMode: "bus",
    travelMinutes: 8,
    stayMinutes: 65,
    estimatedCost: 20000,
    quietScore: 4,
    visualScore: 2,
    indoor: true,
    latitude: 37.5552,
    longitude: 126.9198,
    source: "mock",
    tags: ["따뜻한 음식", "비 오는 날", "부담 적음"],
  },
  {
    id: "hongdae-dinner-alt",
    name: "라이트 누들 바",
    category: "dinner",
    district: "홍대",
    concept: "짧게 먹고 이동하기 쉬운 식사",
    description: "회전이 빠르고 메뉴 선택이 쉬운 누들 바",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 55,
    estimatedCost: 17000,
    quietScore: 3,
    visualScore: 2,
    indoor: true,
    latitude: 37.5558,
    longitude: 126.9215,
    source: "mock",
    tags: ["회전 빠름", "부담 적음", "실내"],
  },
  {
    id: "hongdae-walk",
    name: "보드게임 아지트",
    category: "walk",
    district: "홍대",
    concept: "실내 활동 대체",
    description: "산책 대신 대화형 실내 활동으로 전환하기 좋은 공간",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 70,
    estimatedCost: 12000,
    quietScore: 3,
    visualScore: 3,
    indoor: true,
    latitude: 37.5578,
    longitude: 126.9255,
    source: "mock",
    tags: ["실내", "대화형", "가벼운 템포"],
  },
  {
    id: "gangnam-cafe",
    name: "세컨드 살롱",
    category: "cafe",
    district: "강남",
    concept: "소개팅 안전 카페",
    description: "배경 소음이 낮고 좌석 간격이 넓은 첫 만남용 카페",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 70,
    estimatedCost: 17000,
    quietScore: 5,
    visualScore: 3,
    indoor: true,
    latitude: 37.4982,
    longitude: 127.0284,
    source: "mock",
    tags: ["소음 낮음", "좌석 간격", "소개팅"],
  },
  {
    id: "gangnam-cafe-alt",
    name: "오브제 라운지",
    category: "cafe",
    district: "강남",
    concept: "피크 대응형 소개팅 카페",
    description: "좌석 수가 넓고 대기 분산이 되는 라운지형 카페",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 60,
    estimatedCost: 15000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.4987,
    longitude: 127.0296,
    source: "mock",
    tags: ["좌석 여유", "소개팅", "웨이팅 분산"],
  },
  {
    id: "gangnam-dinner",
    name: "스몰 플레이트 비스트로",
    category: "dinner",
    district: "강남",
    concept: "대화형 식사",
    description: "메뉴 결정 부담이 적고 조용한 좌석 구조를 가진 비스트로",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 73,
    estimatedCost: 24000,
    quietScore: 4,
    visualScore: 3,
    indoor: true,
    latitude: 37.4972,
    longitude: 127.0301,
    source: "mock",
    tags: ["예산 안정", "소개팅 안전", "대화 적합"],
  },
  {
    id: "gangnam-dinner-alt",
    name: "테이블 8 다이너",
    category: "dinner",
    district: "강남",
    concept: "웨이팅 적은 저녁 대안",
    description: "예약 없이도 비교적 빠르게 들어가기 좋은 식사 공간",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 62,
    estimatedCost: 21000,
    quietScore: 4,
    visualScore: 2,
    indoor: true,
    latitude: 37.4966,
    longitude: 127.0295,
    source: "mock",
    tags: ["회전 빠름", "예산 안정", "소개팅 안전"],
  },
  {
    id: "gangnam-walk",
    name: "도심 산책 루프",
    category: "walk",
    district: "강남",
    concept: "짧은 전환 산책",
    description: "식사 후 어색함을 풀고 대화를 이어가기 좋은 짧은 루프",
    transitMode: "walk",
    travelMinutes: 2,
    stayMinutes: 30,
    estimatedCost: 0,
    quietScore: 4,
    visualScore: 2,
    indoor: false,
    latitude: 37.4988,
    longitude: 127.0271,
    source: "mock",
    tags: ["분위기 전환", "대화 연장", "야외"],
  },
  {
    id: "gangnam-bar",
    name: "하이볼 스튜디오",
    category: "bar",
    district: "강남",
    concept: "가볍게 선택하는 2차",
    description: "부담 없는 잔술 위주로 이어가기 좋은 바",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 50,
    estimatedCost: 12000,
    quietScore: 3,
    visualScore: 3,
    indoor: true,
    latitude: 37.5003,
    longitude: 127.0312,
    source: "mock",
    tags: ["가볍게", "2차 선택형", "실내"],
  },
  {
    id: "eulji-gallery",
    name: "피크닉 전시관",
    category: "gallery",
    district: "을지로",
    concept: "감도 높은 스타트",
    description: "대화와 사진을 동시에 열어주는 전시형 장소",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 70,
    estimatedCost: 36000,
    quietScore: 4,
    visualScore: 5,
    indoor: true,
    latitude: 37.5643,
    longitude: 126.9797,
    source: "mock",
    tags: ["사진 포인트", "실내", "몰입형"],
  },
  {
    id: "eulji-cafe",
    name: "호텔 라운지 카페",
    category: "cafe",
    district: "을지로",
    concept: "디테일 있는 휴식",
    description: "식사 전 긴장을 풀고 분위기를 올리기 좋은 라운지",
    transitMode: "taxi",
    travelMinutes: 7,
    stayMinutes: 60,
    estimatedCost: 24000,
    quietScore: 4,
    visualScore: 5,
    indoor: true,
    latitude: 37.5652,
    longitude: 126.9814,
    source: "mock",
    tags: ["라운지", "뷰", "디저트"],
  },
  {
    id: "eulji-cafe-alt",
    name: "프레임 커피바",
    category: "cafe",
    district: "을지로",
    concept: "짧게 쉬는 무드 카페",
    description: "좌석 회전이 빨라 일정이 밀릴 때 대응하기 좋은 커피바",
    transitMode: "walk",
    travelMinutes: 5,
    stayMinutes: 45,
    estimatedCost: 16000,
    quietScore: 3,
    visualScore: 4,
    indoor: true,
    latitude: 37.5657,
    longitude: 126.9808,
    source: "mock",
    tags: ["회전 빠름", "무드 조명", "실내"],
  },
  {
    id: "eulji-dinner",
    name: "르 시엘 다이닝",
    category: "dinner",
    district: "을지로",
    concept: "야간 무드 강화",
    description: "야경과 서비스 모두 강점인 기념일용 다이닝",
    transitMode: "taxi",
    travelMinutes: 9,
    stayMinutes: 95,
    estimatedCost: 68000,
    quietScore: 4,
    visualScore: 5,
    indoor: true,
    latitude: 37.5661,
    longitude: 126.9821,
    source: "mock",
    tags: ["야경", "기념일", "예약 추천"],
  },
  {
    id: "eulji-dinner-alt",
    name: "을지 다이닝 스튜디오",
    category: "dinner",
    district: "을지로",
    concept: "기념일 톤을 유지하는 대안 식사",
    description: "야경보다는 안정적인 좌석 운영이 강점인 다이닝",
    transitMode: "walk",
    travelMinutes: 7,
    stayMinutes: 78,
    estimatedCost: 42000,
    quietScore: 4,
    visualScore: 4,
    indoor: true,
    latitude: 37.5654,
    longitude: 126.9817,
    source: "mock",
    tags: ["무드 유지", "웨이팅 완화", "실내"],
  },
  {
    id: "eulji-bar",
    name: "레코드 하이볼",
    category: "bar",
    district: "을지로",
    concept: "퇴근 후 가볍게 이어지는 2차",
    description: "하이볼과 음악이 강점인 을지로형 캐주얼 바",
    transitMode: "walk",
    travelMinutes: 6,
    stayMinutes: 55,
    estimatedCost: 15000,
    quietScore: 3,
    visualScore: 4,
    indoor: true,
    latitude: 37.5668,
    longitude: 126.9904,
    source: "mock",
    tags: ["하이볼", "캐주얼", "실내"],
  },
  {
    id: "eulji-walk",
    name: "청계 루프 산책",
    category: "walk",
    district: "을지로",
    concept: "짧게 정리하는 야간 산책",
    description: "식사나 술 이후 템포를 부드럽게 정리하기 좋은 짧은 산책 루프",
    transitMode: "walk",
    travelMinutes: 4,
    stayMinutes: 28,
    estimatedCost: 0,
    quietScore: 4,
    visualScore: 3,
    indoor: false,
    latitude: 37.5681,
    longitude: 126.9889,
    source: "mock",
    tags: ["야간 무드", "대화 연장", "야외"],
  },
];
